#!/usr/bin/env python3
"""Generate Constants.g.cs (CipherBlob only) and the SYSTEM-only key.bin
staging file for CredService.exe from flags/manifest.yaml.

  - AES-128 key = the 16 raw bytes of m6.s2's UUID; written to
    re_bait/CredService/key.bin, baked into the VM at
    C:\\ProgramData\\CredService\\key.bin with SDDL D:P(A;;FA;;;SY) (SYSTEM-only).
  - CipherBlob (in Constants.g.cs) = m6.s3's UUID encrypted with that key
    (12B nonce || ct || 16B GCM tag).

Usage:
    seed_credservice.py [--manifest PATH] [--out-cs PATH] [--out-key PATH]
"""
import argparse
import hashlib
import os
import sys
import uuid
from pathlib import Path

try:
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM
except ImportError:
    print("ERROR: cryptography not installed (pip install cryptography)", file=sys.stderr)
    sys.exit(1)

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML not installed (pip install pyyaml)", file=sys.stderr)
    sys.exit(1)

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_MANIFEST = REPO_ROOT / "flags" / "manifest.yaml"
DEFAULT_OUT_CS = REPO_ROOT / "re_bait" / "CredService" / "Constants.g.cs"
DEFAULT_OUT_KEY = REPO_ROOT / "re_bait" / "CredService" / "key.bin"


def csharp_bytearray(name: str, data: bytes) -> str:
    """Pretty-print a byte[] literal with 16 bytes per line."""
    body_lines = []
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02X}" for b in data[i : i + 16])
        body_lines.append(f"        {chunk},")
    body = "\n".join(body_lines)
    return f"    internal static readonly byte[] {name} = new byte[]\n    {{\n{body}\n    }};"


def load_m6_uuids(manifest_path: Path) -> dict[str, str]:
    with manifest_path.open() as f:
        manifest = yaml.safe_load(f)
    out: dict[str, str] = {}
    for entry in manifest["flags"]:
        if entry["id"] in ("m6.s1", "m6.s2", "m6.s3"):
            out[entry["id"]] = entry["uuid"]
    missing = {"m6.s1", "m6.s2", "m6.s3"} - out.keys()
    if missing:
        raise SystemExit(f"manifest missing M6 entries: {sorted(missing)}")
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", default=str(DEFAULT_MANIFEST))
    ap.add_argument("--out-cs", default=str(DEFAULT_OUT_CS),
                    help="path to write Constants.g.cs")
    ap.add_argument("--out-key", default=str(DEFAULT_OUT_KEY),
                    help="path to write key.bin (16 raw bytes; baked into the VM by m6_bake_installers.sh)")
    ap.add_argument(
        "--print-service-tag",
        action="store_true",
        help="Print the m6.s1 UUID to stdout (used by the bake script to "
        "feed -p:ServiceTag to dotnet publish) and exit without writing.",
    )
    args = ap.parse_args()

    uuids = load_m6_uuids(Path(args.manifest))

    if args.print_service_tag:
        print(uuids["m6.s1"])
        return

    # m6.s2 UUID -> 16-byte AES-128 key (canonical big-endian UUID bytes)
    key = uuid.UUID(uuids["m6.s2"]).bytes
    assert len(key) == 16

    # m6.s3 plaintext = the UUID string. Encrypt with AES-128-GCM.
    plaintext = uuids["m6.s3"].encode()
    nonce = os.urandom(12)
    aesgcm = AESGCM(key)
    ct_with_tag = aesgcm.encrypt(nonce, plaintext, associated_data=None)
    ct = ct_with_tag[:-16]
    tag = ct_with_tag[-16:]
    # Layout: nonce(12) || ct || tag(16)  -- Program.cs's TryDecrypt
    # slices CipherBlob[..12] / [12..^16] / [^16..] in that order.
    cipher_blob = nonce + ct + tag

    # Self-test: round-trip decrypt to catch a bad build before it
    # reaches the VM.
    rt = aesgcm.decrypt(nonce, ct + tag, None)
    assert rt == plaintext, "round-trip decrypt failed"

    # ---- Write Constants.g.cs (CipherBlob only) ----
    out_cs_text = f"""// AUTO-GENERATED by scripts/seed_credservice.py -- do not edit.
namespace Nilgiri.CredService;

internal static class Constants
{{
{csharp_bytearray("CipherBlob", cipher_blob)}
}}
"""
    out_cs_path = Path(args.out_cs)
    out_cs_path.parent.mkdir(parents=True, exist_ok=True)
    out_cs_path.write_text(out_cs_text)

    # ---- Write key.bin (16 raw bytes) ----
    out_key_path = Path(args.out_key)
    out_key_path.parent.mkdir(parents=True, exist_ok=True)
    out_key_path.write_bytes(key)

    # ---- Write cipherblob.bin (the 64-byte AES-GCM blob) ----
    # Used as the m6.s3 RE oracle by smoke_m6_credservice.sh: it locates
    # these exact bytes in the deployed CredService.exe (proving the RE
    # target is present) then decrypts them with the m6.s2 key. The
    # entropy-scan extractor is too slow on the ~70MB single-file binary.
    out_blob_path = out_key_path.parent / "cipherblob.bin"
    out_blob_path.write_bytes(cipher_blob)

    print(f"wrote {out_cs_path}")
    print(f"  CipherBlob  {len(cipher_blob)} bytes (nonce 12 + ct {len(ct)} + tag 16)")
    print(f"  ServiceTag  {uuids['m6.s1']} (pass via -p:ServiceTag to dotnet publish)")
    print(f"wrote {out_key_path}")
    print(f"  key.bin     {len(key)} bytes (m6.s2 UUID raw)")
    # SHA-256 of the cipherblob for verify_hardening regression tracking.
    cb_sha = hashlib.sha256(cipher_blob).hexdigest()
    print(f"  cipherblob_sha256={cb_sha}")


if __name__ == "__main__":
    main()
